# Form implementation generated from reading ui file 'C:\dev\python\jwies\src\ui\connect_pane.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_connect_pane(object):
    def setupUi(self, connect_pane):
        connect_pane.setObjectName("connect_pane")
        connect_pane.resize(259, 119)
        self.gridLayout = QtWidgets.QGridLayout(connect_pane)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=connect_pane)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.line_name = QtWidgets.QLineEdit(parent=connect_pane)
        self.line_name.setObjectName("line_name")
        self.gridLayout.addWidget(self.line_name, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=connect_pane)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.line_host = QtWidgets.QLineEdit(parent=connect_pane)
        self.line_host.setObjectName("line_host")
        self.gridLayout.addWidget(self.line_host, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=connect_pane)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.spin_port = QtWidgets.QSpinBox(parent=connect_pane)
        self.spin_port.setMinimum(1)
        self.spin_port.setMaximum(66000)
        self.spin_port.setProperty("value", 9999)
        self.spin_port.setObjectName("spin_port")
        self.gridLayout.addWidget(self.spin_port, 2, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=connect_pane)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 3, 0, 1, 2)

        self.retranslateUi(connect_pane)
        self.buttonBox.accepted.connect(connect_pane.accept) # type: ignore
        self.buttonBox.rejected.connect(connect_pane.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(connect_pane)

    def retranslateUi(self, connect_pane):
        _translate = QtCore.QCoreApplication.translate
        connect_pane.setWindowTitle(_translate("connect_pane", "Connect to a game"))
        self.label.setText(_translate("connect_pane", "Your name:"))
        self.label_3.setText(_translate("connect_pane", "Host address:"))
        self.line_host.setText(_translate("connect_pane", "localhost"))
        self.label_2.setText(_translate("connect_pane", "Port:"))
